"""add_user_analytics_fields

Revision ID: 15aa610c2783
Revises: d5d01d2f6610
Create Date: 2025-10-14 04:35:25.338877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15aa610c2783'
down_revision = 'd5d01d2f6610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('browser_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('device_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('operating_system', sa.String(), nullable=True))
    op.add_column('users', sa.Column('browser_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('browser_version', sa.String(), nullable=True))
    op.add_column('users', sa.Column('screen_resolution', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'screen_resolution')
    op.drop_column('users', 'browser_version')
    op.drop_column('users', 'browser_name')
    op.drop_column('users', 'operating_system')
    op.drop_column('users', 'device_type')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'browser_language')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('users', 'ip_address')
    # ### end Alembic commands ###
