"""Add new fields to Lead model

Revision ID: d5d01d2f6610
Revises: ac775b6dc6c7
Create Date: 2025-10-12 01:10:14.749382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d01d2f6610'
down_revision = 'ac775b6dc6c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('reviews', sa.Column('author', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('reviews', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reviews', 'is_published')
    op.drop_column('reviews', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('content', sa.TEXT(), nullable=False))
    op.add_column('reviews', sa.Column('is_published', sa.BOOLEAN(), nullable=True))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'status')
    op.drop_column('reviews', 'image_url')
    op.drop_column('reviews', 'is_student')
    op.drop_column('reviews', 'text')
    op.drop_column('reviews', 'author')
    op.alter_column('leads', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
